select STARNAME
from STARSIN
where MOVIETITLE = 'The Usual Suspects'
INTERSECT
Select NAME
from MOVIESTAR
where GENDER = 'm'

select STARNAME
from STARSIN, STUDIO
where MOVIEYEAR = 1995 AND STUDIO.NAME = 'MGM'

select MOVIEEXEC.NAME
from MOVIEEXEC, MOVIE
where STUDIONAME = 'MGM' AND CERT# = PRODUCERC#

select M1.TITLE
from MOVIE AS M1, MOVIE AS M2
where M2.TITLE = 'Star Wars' AND M1.LENGTH > M2.LENGTH

select N1.NAME
from MOVIEEXEC AS N1, MOVIEEXEC AS N2
where N2.NAME = 'Stephen Spielberg' AND N1.NETWORTH > N2.NETWORTH

select TITLE
from MOVIE, MOVIEEXEC AS ME1, MOVIEEXEC AS ME2
Where ME2.NAME='Stephen Spielberg' AND ME1.NETWORTH > ME2.NETWORTH AND ME1.CERT# = MOVIE.PRODUCERC#